# Generated by Django 4.0.4 on 2022-05-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_drinks_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorys',
            table='categorys',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
