# Generated by Django 4.0.4 on 2022-05-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_categorys_table_alter_menu_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='drink',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.drinks'),
        ),
    ]
